apiVersion: v1
kind: Service
metadata:
  name: docker-demo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30001
  selector:
    app: docker-demo