apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-demo
spec:
  # 节点数，设置为多个可以实现负载均衡效果
  replicas: 1
  selector:
    app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - name: docker-demo
       #镜像名
       image: docker-demo
       #本地有镜像就不会去仓库拉取
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 8080